name: CLA 📝

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  cla:
    uses: omnidotdev/.github/.github/workflows/cla.yml@847e859140bdea7053aac6d777f296e5f94f9b4c # master
    permissions:
      actions: read
      contents: write
      pull-requests: write
      statuses: write
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
